name: tig_ep_bluetooth
description: A new Flutter package project.
version: 0.0.8
homepage: https://github.com/liunina/tig_ep_bluetooth

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  rxdart: ^0.27.0
  tig_ep_utils: ^0.0.4
  tig_bluetooth_basic: ^0.0.4
  blue_thermal_printer: ^1.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
